version: '3.9'

services:
  api-basic:
    image: api-basic:latest
    ports:
      - "3000:3000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongo-api
    environment:
      MONGO_INITDB_ROOT_USERNAME: maykol
      MONGO_INITDB_ROOT_PASSWORD: 123456
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: